## Shoplist Examples

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.random.seed(0)
week_sales = np.random.randint(20,size =(5,3))
week_sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [21]:
week_sales_df = pd.DataFrame(week_sales,
                            index = ["Pzt","Sali","Cars","Pers","Cuma"],
                            columns = ["Mouse(Adet)","Klavye(Adet)","Bilgisayar(Adet)"])
week_sales_df

Mouse(Adet)  Klavye(Adet)  Bilgisayar(Adet)
Pzt            12            15                 0
Sali            3             3                 7
Cars            9            19                18
Pers            4             6                12
Cuma            1             6                 7

In [18]:
prices = np.random.randint(50,70,size =(3,1))
prices , prices.T

(array([[50],
        [60],
        [53]]),
 array([[50, 60, 53]]))

In [20]:
prices_df = pd.DataFrame(prices.T,
                        index = ["Prices"],
                        columns = ["Mouse(TL)","Klavye(TL)","Bilgisayar(TL)"])
prices_df

Mouse(TL)  Klavye(TL)  Bilgisayar(TL)
Prices         50          60              53

In [24]:
week_sales_df["Total(TL)"] = np.dot(week_sales,prices)
week_sales_df

Mouse(Adet)  Klavye(Adet)  Bilgisayar(Adet)  Total(TL)
Pzt            12            15                 0       1500
Sali            3             3                 7        701
Cars            9            19                18       2544
Pers            4             6                12       1196
Cuma            1             6                 7        781

In [25]:
50*12 + 15*60

1500

In [26]:
week_sales_df.to_csv("Week_Sales.csv")